# Generated by Django 4.2 on 2023-05-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_nome_contacts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
