# Generated by Django 4.2 on 2023-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
